# Generated by Django 5.0.6 on 2024-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('manager', 'Manager'), ('intern', 'Intern'), ('admin', 'Admin')], default='', max_length=10),
        ),
    ]
