# Generated by Django 5.0.6 on 2024-12-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_goal_assigned_to_goal_completed_goal_created_at_and_more'),
        ('accounts', '0015_remove_performancereview_manager'),
    ]

    operations = [
    ]
