# Generated by Django 5.0.6 on 2024-12-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20241216_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('achieved', 'Achieved'), ('missed', 'Missed')], default='in_progress'),
        ),
    ]
