# Generated by Django 5.0.6 on 2024-12-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_goal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(default='Untitled Goal', max_length=100, null=True),
        ),
    ]
