# Generated by Django 5.1.1 on 2024-12-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20241216_1223'),
        ('accounts', '0018_alter_goal_title'),
    ]

    operations = [
    ]
