# Generated by Django 5.1.1 on 2024-12-16 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_0016_merge_20241216_1223_0018_alter_goal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
