# Generated by Django 5.0.6 on 2025-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_performancereview_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('achieved', 'Achieved'), ('missed', 'Missed')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
